### ISSUE TITLE
Timed out Jira

### ISSUE THREAD

**Issue by vagnersabadi** [johannesjo/super-productivity-chrome-extension#1]
Version:
[ v1.10.56 ]

Current behavior:
When you click credential test a message occurs: Jira Request timed out for searchJira

Expected behavior:
Sync with Jira

![Captura de Tela 2020-01-14 às 17 19 32](https://user-images.githubusercontent.com/12532889/72380256-c21f3780-36f3-11ea-89a4-f6b1e45a03a6.png)

**Comment by johannesjo** [comment]
The 1.X.X branch is not actively developed any more. Please have a look here to find the latest version:
https://github.com/johannesjo/super-productivity

I'd recommend downloading this version first before upgrading tot the latest one, as it is the last version providing a migration of the 1.X.X data.
https://github.com/johannesjo/super-productivity/releases/tag/v2.10.12
